const BoardList = [
  "CBSE",
  "ICSE",
  "NCERT",
  "IGOT-Health",
  "NIOS",
  "CISCE",
  "CAIE",
  "State (Andhra Pradesh)",
  "State (Arunachal Pradesh)",
  "State (Assam)",
  "State (Bihar)",
  "State (Chandigarh)",
  "State (Chhattisgarh)",
  "State (Gujarat)",
  "State (Haryana)",
  "State (Himachal Pradesh)",
  "State (Jharkhand)",
  "State (Karnataka)",
  "State (Kerala)",
  "State (Madhya Pradesh)",
  "State (Maharashtra)",
  "State (Manipur)",
  "State (Meghalay)",
  "State (Mizoram)",
  "State (Nagaland)",
  "State (Odisha)",
  "State (Panjab)",
  "State (Rajasthan)",
  "State (Sikkim)",
  "State (Tamil Nadu)",
  "State (Telangana)",
  "State (Tripura)",
  "State (Uttar Pradesh)",
  "State (Uttrakhand)",
  "UT (Andaman and Nicobar Islands)",
  "UT (Ladakh)",
  "UT (Puducerry)",
];

const LanguagesList = [
  "English",
  "Marathi",
  "Hindi",
  "Kannada",
  "Oriya",
  "Tamil",
  "Telagu",
  "Urdu",
  "Sanskrit",
  "Assamese",
  "Bangali",
  "Bodo",
  "Garo",
  "Hmar",
  "Karbi",
  "Manipuri",
  "Mising",
  "Rabha",
  "Arabi",
  "Arabic",
  "Persian",
  "Pharsi",
  "French",
  "Konakni",
  "Portuguese",
  "Gujarati",
  "Khadiya",
  "Kurukh",
  "Mundari",
  "Malayalam",
  "Nepali",
  "Mizo",
  "Panjabi",
];

export { BoardList, LanguagesList };
